gcp_vm_project_id: "{{ lookup('ansible.builtin.env', 'GCP_PROJECT_ID') }}"
gcp_vm_auth_kind: "application"
gcp_vm_region: "{{ lookup('ansible.builtin.env', 'GCP_REGION') | default('europe-west3', true) }}"
gcp_vm_zone: "{{ lookup('ansible.builtin.env', 'GCP_ZONE') | default('europe-west3-a', true) }}"
gcp_vm_network_name: "{{ lookup('ansible.builtin.env', 'GCP_NETWORK') | default('gcp-ansible-network', true) }}"
gcp_vm_subnet_name: "{{ lookup('ansible.builtin.env', 'GCP_SUBNET') | default('gcp-ansible-subnet', true) }}"
gcp_vm_firewall_name: "{{ lookup('ansible.builtin.env', 'GCP_FIREWALL') | default('gcp-ansible-allow-ssh', true) }}"
gcp_vm_instance_name: "{{ lookup('ansible.builtin.env', 'GCP_INSTANCE') | default('gcp-ansible-vm', true) }}"
gcp_vm_machine_type: "{{ lookup('ansible.builtin.env', 'GCP_MACHINE_TYPE') | default('e2-micro', true) }}"
gcp_vm_image_project: "{{ lookup('ansible.builtin.env', 'GCP_IMAGE_PROJECT') | default('debian-cloud', true) }}"
gcp_vm_image_family: "{{ lookup('ansible.builtin.env', 'GCP_IMAGE_FAMILY') | default('debian-12', true) }}"
