---
# Use the same Python interpreter that started Ansible for local modules.
ansible_python_interpreter: "{{ ansible_playbook_python }}"
# Replace this value with your Google Cloud project ID.
gcp_vm_project_id: "project-c64d491a-e81c-47b9-9b7"
